# Generated by Django 5.2 on 2025-05-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepensePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='pdfs/depenses/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('depense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.depense')),
            ],
        ),
        migrations.CreateModel(
            name='RevenuPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='pdfs/revenus/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('revenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.revenu')),
            ],
        ),
    ]
