# Generated by Django 5.2 on 2025-05-13 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_depensepdf_revenupdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('motif', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('banque_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='app.categoriebank')),
                ('banque_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='app.categoriebank')),
            ],
        ),
    ]
