# Generated by Django 5.2 on 2025-05-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_banktransfert'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Choisir le mois du budget (ex: 2025-06-01)')),
                ('montant_planifie', models.DecimalField(decimal_places=0, max_digits=12)),
                ('type', models.CharField(choices=[('depense', 'Dépense'), ('epargne', 'Épargne'), ('achat', 'Achat'), ('autre', 'Autre')], max_length=10)),
                ('objectif', models.CharField(blank=True, max_length=255)),
                ('prioritaire', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriedepense')),
            ],
            options={
                'verbose_name': 'Budget mensuel',
                'verbose_name_plural': 'Budgets mensuels',
                'unique_together': {('mois', 'categorie')},
            },
        ),
    ]
